### ISSUE TITLE
DB_RaceTags Error

### ISSUE THREAD

**Issue by Kitthaven** [BG3-Community-Library-Team/TagFramework#1]
I got this error when removing the REALLY tag line in the config:

`bg3se::esv::lua::OsirisCallbackManager::RunHandler(): Osiris event handler failed: [string "TagFramework/Listeners/DB_RaceTags.lua"]:5: String expected for argument 3, got nil
stack traceback:
        [C++ Code]: in field 'DB_RaceTags'
        TagFramework/Listeners/DB_RaceTags.lua:5: in function <TagFramework/Listeners/DB_RaceTags.lua:2>`

**Comment by NellsRelo** [comment]
Resolved in Release 1.1.0+
